# Generated by Django 2.2.12 on 2020-05-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('self', 'Self'), ('client', 'Client')], default='client', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contact_number', models.CharField(max_length=15)),
                ('website', models.URLField(blank=True)),
            ],
        ),
    ]
