# Generated by Django 2.2.12 on 2020-05-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='price',
        ),
        migrations.AddField(
            model_name='company',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='company',
            name='amount_to_be_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='company',
            name='remarks',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
