# Generated by Django 2.2.12 on 2020-05-10 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_profile_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='recorded_by',
        ),
    ]
