# Generated by Django 2.2.12 on 2020-05-14 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20200512_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_type',
            field=models.CharField(choices=[('SA', 'Super Admin'), ('SU', 'Super User'), ('CA', 'Client Admin'), ('CU', 'Client User'), ('YM', 'Yard Manager'), ('PM', 'Project Manager')], default=1, max_length=15),
            preserve_default=False,
        ),
    ]
