# Generated by Django 2.2.12 on 2020-05-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_profile_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='account_type',
            field=models.CharField(choices=[('SA', 'System Admin'), ('SU', 'System User'), ('CA', 'Client Admin'), ('CU', 'Client User'), ('YM', 'Yard Manager'), ('PM', 'Project Manager')], max_length=15),
        ),
    ]
