# Generated by Django 2.2.12 on 2020-04-22 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productregister_productsecondhandsellingrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='productregister',
            name='productCleaningRate',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
