# Generated by Django 2.2.12 on 2020-04-22 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productregister_productcleaningrate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productregister',
            old_name='productWeekyHireCharge',
            new_name='productWeeklyHireCharge',
        ),
    ]
