# Generated by Django 2.2.12 on 2020-04-22 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20200422_1110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productregister',
            old_name='productWeekyRentalRate',
            new_name='productWeeklyRentalRate',
        ),
    ]
