# Generated by Django 2.2.12 on 2020-04-22 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20200422_1112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productregister',
            old_name='productName',
            new_name='product_Name',
        ),
    ]
