# Generated by Django 2.2.12 on 2020-04-25 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20200422_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productregister',
            old_name='product_Name',
            new_name='productName',
        ),
    ]
