# Generated by Django 2.2.12 on 2020-04-28 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20200425_2037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productregister',
            options={'ordering': ['productName']},
        ),
    ]
