# Generated by Django 2.2.12 on 2020-05-12 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20200501_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productregister',
            name='supplierName',
        ),
        migrations.AddField(
            model_name='productregister',
            name='image',
            field=models.ImageField(default='product_pics/default.png', upload_to='product_pics'),
        ),
        migrations.AlterField(
            model_name='productregister',
            name='productRecordedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
