# Generated by Django 2.2.12 on 2020-05-19 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20200512_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productregister',
            old_name='productMaterialItemCode',
            new_name='productItemCode',
        ),
    ]
