# Generated by Django 2.2.12 on 2020-04-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectTitle', models.CharField(max_length=100)),
                ('projectId', models.IntegerField()),
                ('projectContractNo', models.IntegerField()),
                ('projectSiteLocation', models.CharField(max_length=100)),
                ('projectMailLocation', models.CharField(max_length=100)),
                ('orderNumber', models.IntegerField()),
                ('projectStatus', models.CharField(max_length=100)),
                ('projectRecordedBy', models.CharField(max_length=100)),
                ('txTruckRates', models.IntegerField()),
                ('remarks', models.CharField(max_length=100)),
            ],
        ),
    ]
