# Generated by Django 2.2.12 on 2020-05-09 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('project', '0002_auto_20200501_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectregister',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.Company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectregister',
            name='orderNumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projectregister',
            name='projectMailLocation',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='projectregister',
            name='projectRecordedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectregister',
            name='projectStatus',
            field=models.CharField(choices=[('running', 'Running'), ('completed', 'Completed')], max_length=100),
        ),
        migrations.AlterField(
            model_name='projectregister',
            name='remarks',
            field=models.CharField(max_length=255),
        ),
    ]
