# Generated by Django 2.2.12 on 2020-05-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20200509_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectregister',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='projectregister',
            name='amount_to_be_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='projectregister',
            name='projectStatus',
            field=models.CharField(choices=[('Running', 'Running'), ('Completed', 'Completed')], max_length=100),
        ),
    ]
