# Generated by Django 2.2.12 on 2020-05-22 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20200512_1852'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectregister',
            options={'ordering': ['projectTitle']},
        ),
    ]
