# Generated by Django 2.2.12 on 2020-05-22 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20200522_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectregister',
            name='projectMailLocation',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
