# Generated by Django 2.2.12 on 2020-04-28 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplierId', models.IntegerField()),
                ('supplierName', models.CharField(max_length=100)),
                ('supplierAddress', models.CharField(max_length=100)),
                ('supplierUrl', models.URLField(max_length=2083)),
                ('supplierContactPerson', models.CharField(max_length=100)),
                ('supplierContact1', models.CharField(max_length=30)),
                ('supplierContact2', models.CharField(max_length=30)),
                ('supplierContactFax', models.CharField(max_length=100)),
                ('supplierEmail', models.EmailField(max_length=100)),
            ],
        ),
    ]
