# Generated by Django 2.2.12 on 2020-04-28 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierregister',
            name='supplierId',
        ),
    ]
