# Generated by Django 2.2.12 on 2020-04-30 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_remove_supplierregister_supplierid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplierregister',
            options={'ordering': ['supplierName']},
        ),
    ]
