# Generated by Django 2.2.12 on 2020-05-22 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('itemCode', models.CharField(max_length=100)),
                ('sellingRate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cleaningRate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dailyRentalRate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
