# Generated by Django 2.2.12 on 2020-05-22 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductRegister',
        ),
    ]
